<template>
  <v-container>
    <text-page-title>{{ title }}</text-page-title>
    <div v-html="comment"></div>
    <v-select v-model="selected" :items="categories" filled label="カテゴリー"></v-select>
    <list-links-collection :items="items" :category="selected"></list-links-collection>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    title: '一次情報リンク集',
    comment:
      '<p>電子図書館や、電子化された図書や雑誌など、一次情報（源情報、本文そのもの）を入手できるサイトを集めました。</p><p>なお、当館所蔵の電子化された一次資料は「FAIRフェリス女学院大学学術機関リポジトリ」並びに「電子コレクション」に収録しています。</p>',
    categories: [
      '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
      '新聞／ニュース',
      '書評／書評紙・誌',
      '統計／白書／議事録',
      '学術情報',
      '法律',
      '辞書／事典／翻訳（無料サイト）'
    ],
    selected: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
    items: [
      {
        name: '国立国会図書館デジタルコレクション',
        url: 'http://dl.ndl.go.jp/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: false,
        author: '国立国会図書館',
        text: '国立国会図書館で収集・保存しているデジタル資料を検索・閲覧できる',
      },
      {
        name: 'CiNii Articles',
        url: 'http://ci.nii.ac.jp/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: false,
        author: '国立情報学研究所',
        text: '雑誌論文を検索し、掲載されている雑誌名、巻号、ページ数などを参照できるほか、参考文献、その論文を引用した文献、本文（PDF）を表示できる',
      },
      {
        name: '青空文庫',
        url: 'http://www.aozora.gr.jp/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: false,
        author: '（青空文庫）',
        text: '著作権が切れた作品をテキスト、HTML、エキスパンドブックの形で無料公開',
      },
      {
        name: 'Bibliomania',
        url: 'http://www.bibliomania.com/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: true,
        author: '	Internet Public Library',
        text: '古典文学、一般小説、戯曲、ノンフィクションなどを電子化して無料で提供',
      },
      {
        name: 'California Digital Library',
        url: 'http://www.cdlib.org/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: true,
        author: 'University of California',
        text: 'UCの9つのキャンパスの蔵書を横断検索できるMELVIL、電子化された資料にアクセスできるthe Online Archive of California (OAC)などを提供',
      },
      {
        name: 'Digital Library (BL top page)',
        url: 'http://www.bl.uk/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: true,
        author: 'BL',
        text: '電子化した蔵書の提供、オンラインサービス',
      },
      {
        name: 'Keeping America Informed',
        url: 'https://www.gpo.gov/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: true,
        author: 'GPO: U.S.Government Publishing Office',
        text: '大統領による公文書や政府機関によるレポートなど、米国政府の出版物を提供',
      },
      {
        name: 'CONGRESS.GOV',
        url: 'https://congress.gov/',
        category: '電子図書館 (Digital Library) ／ 電子化された資料とリンク集',
        overseas: true,
        author: 'Library of Congress(LC)',
        text: '制定法、連邦議会議事録、委員会情報など、米国議会文書を公開',
      },
      {
        name: '朝日新聞DIGITAL',
        url: 'http://www.asahi.com/',
        category: '新聞／ニュース',
        overseas: false,
        author: '朝日新聞社',
        text: '都道府県別の最新情報を掲載',
      },
      {
        name: 'カナロコ',
        url: 'http://www.kanaloco.jp/',
        category: '新聞／ニュース',
        overseas: false,
        author: '神奈川新聞社',
        text: '神奈川県内のエリア毎の情報を掲載',
      },
      {
        name: 'KK KYODO NEWS SITE',
        url: 'http://www.kyodo.co.jp/',
        category: '新聞／ニュース',
        overseas: false,
        author: '共同通信社',
        text: '暮らしに関わる最新情報を掲載',
      },
      {
        name: '産経ニュース',
        url: 'http://www.sankei.com/',
        category: '新聞／ニュース',
        overseas: false,
        author: '産経新聞社',
        text: '西日本版「産経WEST」も掲載',
      },
      {
        name: '日本経済新聞',
        url: 'http://www.nikkei.co.jp/',
        category: '新聞／ニュース',
        overseas: false,
        author: '日本経済新聞社',
        text: '都道府県別の最新情報を掲載',
      },
      {
        name: '毎日新聞',
        url: 'http://www.mainichi.co.jp/',
        category: '新聞／ニュース',
        overseas: false,
        author: '毎日新聞社',
        text: '都道府県別の最新情報を掲載',
      },
      {
        name: 'YOMIURI ONLINE',
        url: 'http://www.yomiuri.co.jp/',
        category: '新聞／ニュース',
        overseas: false,
        author: '読売新聞社',
        text: '都道府県別の最新情報と、The Japan News(多言語対応)を掲載',
      },
      {
        name: 'Chicago Tribune',
        url: 'http://www.chicagotribune.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'ローカル／ワールドスポーツ情報を掲載',
      },
      {
        name: 'Financial Times',
        url: 'http://www.ft.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'company / industry viewを提供',
      },
      {
        name: 'Los Angels Times',
        url: 'http://www.latimes.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '各分野の詳細情報、カスタマイズ可',
      },
      {
        name: 'New York Times',
        url: 'http://www.nytimes.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '当日、過去の記事検索機能あり',
      },
      {
        name: 'U.S.A. Today',
        url: 'http://www.usatoday.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '印刷版、オンラインショッピング',
      },
      {
        name: 'Wall Street Journal',
        url: 'http://www.wsj.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'ヨーロッパ、US、アジア版を提供',
      },
      {
        name: 'Washington Post',
        url: 'http://www.washingtonpost.com/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'On Politics、Marketplaceなど独立ページを検索可能',
      },
      {
        name: 'London Daily',
        url: 'http://www.london-daily.co.uk/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'サイト全体の検索が可能',
      },
      {
        name: 'Times',
        url: 'http://www.thetimes.co.uk/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '「Sunday Times」を含む1/1/1996以降の記事を検索',
      },
      {
        name: 'Le Monde（仏）',
        url: 'http://www.lemonde.fr/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '読書欄に定評がある',
      },
      {
        name: 'El Pais（西）',
        url: 'http://www.elpais.es/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: '著名作家による連載あり',
      },
      {
        name: '人民日報網絡版',
        url: 'http://j.peopledaily.com.cn/',
        category: '新聞／ニュース',
        overseas: true,
        author: '人民日報',
        text: '中国語、英語、日本語版が用意されており、1995年以降の記事を検索できる',
      },
      {
        name: 'nna',
        url: 'http://news.nna.jp/',
        category: '新聞／ニュース',
        overseas: true,
        author: '',
        text: 'アジア、オーストラリア、英国の各地編集部から送られてくるニュース記事の「EXPRESS ヘッドライン」、緊急時の「特報」、現地発コラム「テイクオフ」、 国際ビジネス情報満載の「伝言板」、「会議室」、何かと役立つ「リンク集」、週間予報が見られる「各地の天気」などが利用できます。',
      },
      {
        name: '好書好日',
        url: 'http://book.asahi.com/',
        category: '書評／書評紙・誌',
        overseas: false,
        author: '朝日新聞',
        text: '書評、新刊紹介、著者インタビューなど、本に関わる情報を掲載',
      },
      {
        name: '産経ニュース - ライフ - 本',
        url: 'http://www.sankei.com/life/newslist/books-n1.html',
        category: '書評／書評紙・誌',
        overseas: false,
        author: '産経新聞',
        text: '書評や読書に関するニュースを掲載',
      },
      {
        name: '日刊ゲンダイ DIGITAL - BOOKS',
        url: 'https://www.nikkan-gendai.com/articles/index/book/',
        category: '書評／書評紙・誌',
        overseas: false,
        author: '日刊ゲンダイ',
        text: '日刊ゲンダイに掲載された書評と新刊書籍の案内',
      },
      {
        name: 'The Horn Book Magazine',
        url: 'http://www.hbook.com/',
        category: '書評／書評紙・誌',
        overseas: true,
        author: '',
        text: '児童書の書評誌。最新出版情報を掲載',
      },
      {
        name: 'The New York Review of Books',
        url: 'http://www.nybooks.com/nyrev/index.html',
        category: '書評／書評紙・誌',
        overseas: true,
        author: '',
        text: '	有名作家による文学論や社会評論も掲載',
      },
      {
        name: 'TLS (The Times Literary Supplement)',
        url: 'http://www.the-tls.co.uk/',
        category: '書評／書評紙・誌',
        overseas: true,
        author: '',
        text: '権威ある書評紙で、最新号や無料記事を掲載',
      },
      {
        name: '総務省統計局',
        url: 'http://www.stat.go.jp/',
        category: '統計／白書／議事録',
        overseas: false,
        author: '',
        text: '国勢調査など',
      },
      {
        name: '文部科学省 統計情報',
        url: 'http://www.mext.go.jp/b_menu/toukei/',
        category: '統計／白書／議事録',
        overseas: false,
        author: '',
        text: '学校基本調査など',
      },
      {
        name: '内閣府 統計情報・調査結果',
        url: 'http://www.esri.cao.go.jp/',
        category: '統計／白書／議事録',
        overseas: false,
        author: '',
        text: '景気、企業、消費などに関する統計',
      },
      {
        name: '国会会議録検索システム',
        url: 'http://kokkai.ndl.go.jp/',
        category: '統計／白書／議事録',
        overseas: false,
        author: '',
        text: '1回国会（1947年5月開会）以降の本会議、全ての委員会等の会議録を収録',
      },
      {
        name: '女性情報CASS',
        url: 'http://winet.nwec.jp/hbs/index.html',
        category: '統計／白書／議事録',
        overseas: false,
        author: '	NWEC（国立女性教育会館）',
        text: 'NWECおよび他機関が作成したDBを横断検索できる。冊子体の内容一覧『女性及び家族に関する統計データベース研究開発報告書』（1997），緑園3階，102445530，367.2||Ko49もあり',
      },
      {
        name: 'eurostat',
        url: 'http://ec.europa.eu/eurostat/',
        category: '統計／白書／議事録',
        overseas: false,
        author: '',
        text: 'EUの人口、経済といった各種統計データを一部無料で公開',
      },
      {
        name: 'ARIADNE（アリアドネ）',
        url: 'http://ariadne.jp/',
        category: '学術情報',
        overseas: false,
        author: '二木 麻里氏',
        text: '人文、芸術、社会科学分野の情報リンク集。ちくま新書『調査のためのインターネット』(1996)『思考のためのインターネット』(1999)の著者が作成',
      },
      {
        name: 'J-STAGE',
        url: 'https://www.jstage.jst.go.jp/browse/-char/ja',
        category: '学術情報',
        overseas: false,
        author: '国立研究開発法人科学技術振興機構 (JST)',
        text: '日本の学協会が出版した最新の論文を検索し閲覧できる',
      },
      {
        name: 'e-Gav',
        url: 'http://law.e-gov.go.jp/cgi-bin/idxsearch.cgi',
        category: '法律',
        overseas: false,
        author: '総務省行政管理局',
        text: '法令（憲法・法律・政令・勅令・府令・省令）の内容を検索して提供。索引検索と用語検索が可能',
      },
      {
        name: '官報',
        url: 'http://kanpou.npb.go.jp/',
        category: '法律',
        overseas: false,
        author: '財務省印刷局',
        text: 'インターネット版『官報』として、１週間分の官報（本紙、号外、政府調達等）が収録されている',
      },
      {
        name: '裁判所',
        url: 'http://www.courts.go.jp/',
        category: '法律',
        overseas: false,
        author: '裁判所',
        text: '「裁判例情報」では、最近の主な最高裁判例から下級裁主要判決情報まで、各種判例の全文が掲載されており、検索が可能',
      },
      {
        name: '日本・外国の法律・政府行政文書の調べ方',
        url: 'http://ilpdc.law.kyoto-u.ac.jp/',
        category: '法律',
        overseas: false,
        author: '京都大学大学院法学研究科附属国際法政文献資料センター',
        text: '冊子体、CD-ROM、Webなどを使った調べ方を網羅的に収録。主要各国を対象とした海外編もあり',
      },
      {
        name: 'Find Law',
        url: 'http://www.findlaw.com/',
        category: '法律',
        overseas: true,
        author: 'FindLaw',
        text: '法律、法律家、法律関係情報を掲載、検索できる',
      },
      {
        name: 'Meta-Index for U.S. Legal Research',
        url: 'http://hrlibrary.umn.edu/lawform-new.html',
        category: '法律',
        overseas: true,
        author: 'University of Minnesota Human Rights Library',
        text: 'インターネット上にある米国法を検索できる',
      },
      {
        name: 'The WWW Virtual Library - Law',
        url: 'http://www.vlib.org.uk/Law.htm',
        category: '法律',
        overseas: true,
        author: 'The WWW Virtual Library',
        text: 'WWW Virtual Libraryの一部として法律情報を提供。ブラウジング可能',
      },
      {
        name: 'Encyclopedia Britannica',
        url: 'http://www.britannica.com/',
        category: '辞書／事典／翻訳（無料サイト）',
        overseas: false,
        author: 'Britannica.com',
        text: 'Encyclopedia BritannicaとWebサイト、雑誌や図書などを同時に検索',
      },
      {
        name: 'goo辞書',
        url: 'http://dictionary.goo.ne.jp/',
        category: '辞書／事典／翻訳（無料サイト）',
        overseas: false,
        author: 'goo',
        text: '大辞泉、プログレッシブ和英中辞典、デイリーコンサイス日中辞典などを収録',
      },
      {
        name: 'RNN 時事英語辞典',
        url: 'http://rnnnews.jp/',
        category: '辞書／事典／翻訳（無料サイト）',
        overseas: false,
        author: 'RNN',
        text: '最新の英語ニュースで多用されるキーワードを、用例とともに掲載',
      },
    ],
  }),
  head() {
    return {
      title: this.title,
    }
  },
}
</script>
