name: Production Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Archive Production Artifact
        # generateしたdistフォルダを永続化する
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        # build job で永続化したdistフォルダを取得する
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
        - name: FTP-Deploy-Action
            uses: SamKirkland/FTP-Deploy-Action@4.2.0
            # FTPアップロードアクション（https://github.com/SamKirkland/FTP-Deploy-Action）
            with:
                server: ${{ secrets.PROD_SERVER }}
                # FTPのサーバーアドレス
                username: ${{ secrets.PROD_USERNAME }}
                # FTPのユーザー名
                password: ${{ secrets.PROD_PASSWORD }}
                # FTPのパスワード
                server-dir: /web/sites/ferris06/htdocs/
                # アップロード先のリモートパス
